global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'contacts-api'
    static_configs:
      - targets: ['contacts-api:80']
    metrics_path: '/metrics'

  - job_name: 'consumer'
    static_configs:
      - targets: ['consumidor:80']
    metrics_path: '/metrics'
    
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 15s