apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-consumer
  namespace: contacts-app
  labels:
    app: contacts-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contacts-consumer
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: contacts-consumer
    spec:
      containers:
      - name: contacts-consumer
        image: ${REGISTRY_NAME}/contacts-consumer:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: metrics
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            configMapKeyRef:
              name: connection-strings
              key: DefaultConnection
        resources:
          limits:
            memory: "384Mi"
            cpu: "300m"
          requests:
            memory: "192Mi"
            cpu: "150m"
        livenessProbe:
          httpGet:
            path: /metrics
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: contacts-consumer-service
  namespace: contacts-app
spec:
  selector:
    app: contacts-consumer
  ports:
  - port: 80
    targetPort: metrics
    name: metrics
  type: ClusterIP